language:
- node_js
node_js:
- 4.4.3
script:
- npm run lint
- npm run build
- npm test
after_success:
- npm run doc
notifications:
  slack:
    secure: nxkXDjtcwehxRiJ8OFfi1XhaOWm+/KRGhBtvLmWcMFVSXPc5yfGe0JNN2H5GqoYTMtAYZdsw3791JT5Wm4+F8gZ7uj8A6NeSZ/LQX+h88aPM64gdmq4OUaHP/FrSggHgi2XxrejwNxOV5E3c2hZV/IyPDW5S33Ie3WI9I0OemSmeRokpYutUTzQJa0csX5kuUTzq14iEUbZqUN6wA2Welgfh3FUMXX3oH5/X22zotjnvPkYuD3zoHDCXSi618GX3b7L2hMN3v2ZTCwP/pSieFCkK4ltQ+ZfCgZzo41RKJANMtp3F0c8MpRFicSPIw8pWgIsW9tEfyrvxV28EYCm5Qoi8yOH0O0QAXgINjqh2c5N2XwMY1aMuz1behAn7vQkjIh+oNnraqv1Mfq3T7uW+bz6yC2ZG5IQ8SBYfhaHjBI91NZwQjQUJ+x5bOpxhhwWh1Feco5oui3mSPVXfx1r7XxkZl9mNtsl433b22UChS4oBmnRFCcJvbQbo0Il0nmMt3JJXQSQa21ebgcYKhmVhHInggXcM6NwYdb1UGstz9gXffMGCiDiDJMilQRHF1a4VCKcQaKqwuQIXKPey9ihZ5de14jFgvEXxLU3R08vsTZtLWv6ChztoHhAZOIKWSeqLydFm1t/MLAY92H1GU52hMynpKw83U8YM1YE1kfiYOhY=
